# Generated by Django 4.2.9 on 2024-03-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EC_Admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voters",
            name="assembly",
            field=models.CharField(max_length=20),
        ),
    ]
